spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: admin
  profiles:
    default: "h2"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
jws:
  sharedKey: c3f0ef4a-8f77-4b97-a54d-78b07f3c14b7